### ISSUE TITLE
Lacks environment awareness

### ISSUE THREAD

**Issue by patrikalienus** [cferdinandi/build-tool-boilerplate#26]
I'd like to see (for instance) an awareness of build environment. Running `npm run watch` for instance, should probably mean that we want sourcemaps on, but running `build` probably means we wanna deploy to production, and thus should not have sourcemaps.

All in all, this is a great little tool for those of us tired of fixing gulp all the time :)

**Comment by cferdinandi** [comment]
Hi @patrikalienus, that feels like a great addition that I would encourage you to make for your own projects.

This repository is deliberately built as a boilerplate for people to build on top of and modify. As such, I wouldn't likely add this to the core repository, simply because it's outside the scope of what the project is trying to do.
